# Generated by Django 5.0.7 on 2024-08-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmuebles',
            old_name='m2_cuadrados',
            new_name='m2_construido',
        ),
        migrations.RenameField(
            model_name='inmuebles',
            old_name='estacionamiento',
            new_name='numero_est',
        ),
        migrations.AddField(
            model_name='inmuebles',
            name='m2_terreno',
            field=models.FloatField(default=0),
        ),
    ]
