# Generated by Django 5.0.7 on 2024-08-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0002_rename_m2_cuadrados_inmuebles_m2_construido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebles',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
    ]
