# Generated by Django 5.0.7 on 2024-08-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0003_alter_inmuebles_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
    ]
